(function(){
'use strict';
var state={nodes:[],links:[],adj:new Map(),svg:null,gRoot:null,gLinks:null,gNodes:null,zoom:null,simulation:null,width:0,height:0,selectedNodeId:null,highlightedNodeIds:new Set(),highlightedLinkKeys:new Set()};
var els={
  svg:document.getElementById('village-tree'), treeContainer:document.getElementById('tree-container'), status:document.getElementById('status'),
  familySearch:document.getElementById('family-search'), familyList:document.getElementById('family-list'), relationFrom:document.getElementById('relation-from'), relationTo:document.getElementById('relation-to'), findRelation:document.getElementById('find-relation'), fitView:document.getElementById('fit-view'), clearSelection:document.getElementById('clear-selection'), tooltip:document.getElementById('tooltip'), modal:document.getElementById('family-modal'), modalTitle:document.getElementById('modal-title'), modalText:document.getElementById('modal-text'), modalFamilyLink:document.getElementById('modal-family-link'), modalGenealogyLink:document.getElementById('modal-genealogy-link'), btnRo:document.getElementById('btn-ro'), btnEn:document.getElementById('btn-en'), scrollTop:document.getElementById('scrollTop'), scrollBottom:document.getElementById('scrollBottom'), year:document.getElementById('yr')
};
function lang(){return localStorage.getItem('calnic-lang')||'ro';}
function t(ro,en){return lang()==='en'?en:ro;}
function setStatus(msg){if(els.status) els.status.textContent=msg;}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();}
function linkKey(a,b){return [a,b].sort().join('__');}
function familyPageUrl(node){return 'genealogie-familie.html?family='+encodeURIComponent(node.id);} // keep sync simple
function showModal(node,title,text){
  els.modalTitle.textContent=title||node.name;
  els.modalText.textContent=text||'';
  els.modalGenealogyLink.href='genealogie.html?family='+encodeURIComponent(node.id);
  els.modalFamilyLink.href=node.visibility==='public'?familyPageUrl(node):('genealogie.html?family='+encodeURIComponent(node.id));
  els.modalFamilyLink.textContent=node.visibility==='public'?t('Deschide pagina familiei','Open family page'):t('Vezi in Genealogie','See in Genealogy');
  els.modal.classList.remove('hidden');
}
function hideModal(){els.modal.classList.add('hidden');}
function applyLang(){
  document.querySelectorAll('[data-ro]').forEach(function(el){var v=el.getAttribute('data-'+lang()); if(v!=null){if(el.tagName==='INPUT') el.placeholder=v; else el.textContent=v;}});
  if(els.btnRo) els.btnRo.classList.toggle('active',lang()==='ro');
  if(els.btnEn) els.btnEn.classList.toggle('active',lang()==='en');
}
function initLang(){applyLang(); if(els.btnRo) els.btnRo.onclick=function(){localStorage.setItem('calnic-lang','ro');applyLang();}; if(els.btnEn) els.btnEn.onclick=function(){localStorage.setItem('calnic-lang','en');applyLang();};}
function initScroll(){ if(els.year) els.year.textContent=new Date().getFullYear(); function upd(){var sc=window.scrollY>300, at=(window.innerHeight+window.scrollY)>=document.body.scrollHeight-100; if(els.scrollTop){els.scrollTop.style.opacity=sc?'1':'0';els.scrollTop.style.pointerEvents=sc?'auto':'none';} if(els.scrollBottom){els.scrollBottom.style.opacity=at?'0':'1';els.scrollBottom.style.pointerEvents=at?'none':'auto';}} window.addEventListener('scroll',upd); setTimeout(upd,100); if(els.scrollTop) els.scrollTop.onclick=function(){window.scrollTo({top:0,behavior:'smooth'});} ; if(els.scrollBottom) els.scrollBottom.onclick=function(){window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});} }
function initHamburger(){var h=document.getElementById('hamburgerBtn'),m=document.getElementById('navMobileMenu'); if(!h||!m) return; h.addEventListener('click',function(){var o=m.classList.toggle('open'); h.textContent=o?'✕':'☰';});}
async function waitForSupabase(){ if(window.supabase&&window.supabase.from) return window.supabase; return new Promise(function(resolve){ document.addEventListener('supabase:ready',function(){resolve(window.supabase);},{once:true});}); }
async function loadGraph(){
  var sb=await waitForSupabase();
  var res=await Promise.all([
    sb.from('families').select('id,display_name,village_name,visibility,members_count,generations_count').order('display_name'),
    sb.from('v_family_connections').select('source_family_id,target_family_id,relationship_type'),
    sb.from('family_pages').select('family_id,page_slug,is_public')
  ]);
  var famRes=res[0], linkRes=res[1], pageRes=res[2];
  if(famRes.error) throw famRes.error;
  var pageMap={}; (pageRes.data||[]).forEach(function(p){pageMap[p.family_id]=p;});
  var nodes=(famRes.data||[]).map(function(f){return {id:f.id,name:f.display_name||'Familie',village:f.village_name||'Calnic',visibility:f.visibility||'private',members_count:f.members_count||0,generations_count:f.generations_count||0,pageSlug:pageMap[f.id]&&pageMap[f.id].is_public?pageMap[f.id].page_slug:null};});
  var seen={}; var links=[]; (linkRes.data||[]).forEach(function(r){var k=linkKey(r.source_family_id,r.target_family_id)+'__'+(r.relationship_type||'kinship_other'); if(seen[k]||!r.source_family_id||!r.target_family_id||r.source_family_id===r.target_family_id) return; seen[k]=1; links.push({source:r.source_family_id,target:r.target_family_id,type:r.relationship_type||'kinship_other'});});
  return {nodes:nodes,links:links};
}
function buildAdj(nodes,links){ var m=new Map(nodes.map(function(n){return [n.id,[]];})); links.forEach(function(l){m.get(l.source).push({nodeId:l.target,type:l.type}); m.get(l.target).push({nodeId:l.source,type:l.type});}); return m; }
function populateControls(){ els.familyList.innerHTML=''; els.relationFrom.innerHTML='<option value="">'+t('Alege familia','Choose family')+'</option>'; els.relationTo.innerHTML='<option value="">'+t('Alege familia','Choose family')+'</option>'; state.nodes.forEach(function(n){ var op=document.createElement('option'); op.value=n.name; els.familyList.appendChild(op); var a=document.createElement('option'); a.value=n.id; a.textContent=n.name; els.relationFrom.appendChild(a); var b=document.createElement('option'); b.value=n.id; b.textContent=n.name; els.relationTo.appendChild(b); }); }
function initSvg(){ var rect=els.treeContainer.getBoundingClientRect(); state.width=Math.max(400,rect.width); state.height=760; state.svg=d3.select(els.svg).attr('viewBox',[0,0,state.width,state.height]); state.gRoot=state.svg.append('g'); state.gLinks=state.gRoot.append('g'); state.gNodes=state.gRoot.append('g'); state.zoom=d3.zoom().scaleExtent([0.25,3.5]).on('zoom',function(ev){state.gRoot.attr('transform',ev.transform);}); state.svg.call(state.zoom); }
function renderTooltip(ev,node){ els.tooltip.innerHTML='<strong>'+node.name+'</strong><br>'+t('Status','Status')+': '+(node.visibility==='public'?t('Publica','Public'):t('Privata','Private')); els.tooltip.style.display='block'; els.tooltip.style.left=(ev.offsetX+18)+'px'; els.tooltip.style.top=(ev.offsetY+18)+'px'; }
function hideTooltip(){ els.tooltip.style.display='none'; }
function updateStyles(){ if(!state.gNodes||!state.gLinks) return; state.gNodes.selectAll('g.node').each(function(d){ var isSelected=state.selectedNodeId===d.id; var dim=state.highlightedNodeIds.size>0&&!state.highlightedNodeIds.has(d.id); d3.select(this).select('circle').attr('fill',d.visibility==='public'?'#d4a84a':'#6f7884').attr('stroke',isSelected?'#fff4c2':state.highlightedNodeIds.has(d.id)?'#f4d88a':'#243244').attr('r',isSelected?28:22).attr('opacity',dim?0.22:1); d3.select(this).select('text').attr('opacity',dim?0.25:1).attr('font-weight',isSelected||state.highlightedNodeIds.has(d.id)?700:500); }); state.gLinks.selectAll('line').each(function(d){ var s=typeof d.source==='object'?d.source.id:d.source; var t=typeof d.target==='object'?d.target.id:d.target; var key=linkKey(s,t); var dim=state.highlightedLinkKeys.size>0&&!state.highlightedLinkKeys.has(key); d3.select(this).attr('stroke',state.highlightedLinkKeys.has(key)?'#f4d88a':'#4f5d73').attr('stroke-width',state.highlightedLinkKeys.has(key)?3.8:2).attr('opacity',dim?0.16:0.9); }); }
function fitGraph(duration){ duration=duration||650; if(!state.nodes.length) return; var xs=state.nodes.map(function(n){return n.x||0;}), ys=state.nodes.map(function(n){return n.y||0;}); var minX=Math.min.apply(null,xs)-80,maxX=Math.max.apply(null,xs)+80,minY=Math.min.apply(null,ys)-80,maxY=Math.max.apply(null,ys)+80; var gw=Math.max(1,maxX-minX), gh=Math.max(1,maxY-minY); var scale=Math.min(2.1,0.9/Math.max(gw/state.width,gh/state.height)); var tx=state.width/2-scale*(minX+gw/2), ty=state.height/2-scale*(minY+gh/2); state.svg.transition().duration(duration).call(state.zoom.transform,d3.zoomIdentity.translate(tx,ty).scale(scale)); }
function centerOnNode(node,zoomLevel,duration){ zoomLevel=zoomLevel||1.5; duration=duration||650; if(!node) return; var tx=state.width/2-zoomLevel*node.x, ty=state.height/2-zoomLevel*node.y; state.svg.transition().duration(duration).call(state.zoom.transform,d3.zoomIdentity.translate(tx,ty).scale(zoomLevel)); }
function bfs(from,to){ if(!from||!to) return null; if(from===to) return [from]; var q=[[from]], seen={}; seen[from]=1; while(q.length){ var path=q.shift(), cur=path[path.length-1], neigh=state.adj.get(cur)||[]; for(var i=0;i<neigh.length;i++){ var nid=neigh[i].nodeId; if(seen[nid]) continue; var next=path.concat(nid); if(nid===to) return next; seen[nid]=1; q.push(next);} } return null; }
function highlightPath(path){ state.highlightedNodeIds=new Set(path); state.highlightedLinkKeys=new Set(); for(var i=0;i<path.length-1;i++) state.highlightedLinkKeys.add(linkKey(path[i],path[i+1])); state.selectedNodeId=path[0]||null; updateStyles(); var first=state.nodes.find(function(n){return n.id===path[0];}); if(first) centerOnNode(first,1.2,500); }
function handleNodeClick(ev,node){ ev.stopPropagation(); state.selectedNodeId=node.id; state.highlightedNodeIds=new Set([node.id]); state.highlightedLinkKeys=new Set(); updateStyles(); centerOnNode(node,1.35); if(node.visibility==='private'){ showModal(node,node.name,t('Privat','Private')); setStatus(t('Familia este privata.','Family is private.')); return; } showModal(node,node.name,t('Poti deschide direct pagina familiei sau lista Genealogie.','You can open the family page or the Genealogy list directly.')); setStatus(t('Familie selectata: ','Selected family: ')+node.name); }
function drawGraph(){ state.simulation=d3.forceSimulation(state.nodes).force('link',d3.forceLink(state.links).id(function(d){return d.id;}).distance(function(d){ var s=typeof d.source==='object'?d.source.id:d.source; var t=typeof d.target==='object'?d.target.id:d.target; var sd=(state.adj.get(s)||[]).length, td=(state.adj.get(t)||[]).length; return (sd===0||td===0)?240:145; }).strength(0.65)).force('charge',d3.forceManyBody().strength(function(d){ return ((state.adj.get(d.id)||[]).length===0?-520:-680);})).force('center',d3.forceCenter(state.width/2,state.height/2)).force('collision',d3.forceCollide().radius(function(d){ return ((state.adj.get(d.id)||[]).length===0?54:42);})); var linkSel=state.gLinks.selectAll('line').data(state.links).join('line').attr('stroke','#4f5d73').attr('stroke-width',2).attr('stroke-linecap','round'); var nodeSel=state.gNodes.selectAll('g.node').data(state.nodes).join('g').attr('class','node').call(d3.drag().on('start',function(ev,d){ if(!ev.active) state.simulation.alphaTarget(0.3).restart(); d.fx=d.x; d.fy=d.y; }).on('drag',function(ev,d){d.fx=ev.x; d.fy=ev.y;}).on('end',function(ev,d){ if(!ev.active) state.simulation.alphaTarget(0); d.fx=null; d.fy=null; })); nodeSel.append('circle').attr('r',22).attr('fill',function(d){return d.visibility==='public'?'#d4a84a':'#6f7884';}).attr('stroke','#243244'); nodeSel.append('text').attr('dy',40).text(function(d){return d.name;}); nodeSel.on('mouseover',function(ev,d){renderTooltip(ev,d);}).on('mousemove',function(ev,d){renderTooltip(ev,d);}).on('mouseout',hideTooltip).on('click',handleNodeClick); state.simulation.on('tick',function(){ linkSel.attr('x1',function(d){return d.source.x;}).attr('y1',function(d){return d.source.y;}).attr('x2',function(d){return d.target.x;}).attr('y2',function(d){return d.target.y;}); nodeSel.attr('transform',function(d){return 'translate('+d.x+','+d.y+')';}); }); state.simulation.on('end',function(){ fitGraph(); setStatus(t('Arbore incarcat: ','Tree loaded: ')+state.nodes.length+' '+t('familii','families')+', '+state.links.length+' '+t('conexiuni','connections')); applyQuerySync(); }); updateStyles(); }
function applyQuerySync(){ var sp=new URLSearchParams(location.search), family=sp.get('family'), from=sp.get('from'), to=sp.get('to'); if(from&&to){ els.relationFrom.value=from; els.relationTo.value=to; handleFindRelation(); return; } if(family){ var node=state.nodes.find(function(n){return n.id===family;}); if(node){ state.selectedNodeId=node.id; state.highlightedNodeIds=new Set([node.id]); state.highlightedLinkKeys=new Set(); updateStyles(); centerOnNode(node,1.5); showModal(node,node.name,node.visibility==='public'?t('Ai ajuns aici din Genealogie.','You arrived here from Genealogy.'):t('Familia este privata.','Family is private.')); } } }
function handleFindRelation(){ var from=els.relationFrom.value, to=els.relationTo.value; if(!from||!to){setStatus(t('Alege ambele familii.','Choose both families.')); return;} var path=bfs(from,to); if(!path){ state.highlightedNodeIds.clear(); state.highlightedLinkKeys.clear(); updateStyles(); setStatus(t('Nu exista relatie documentata intre familiile selectate.','No documented relation exists between selected families.')); hideModal(); return; } highlightPath(path); var names=path.map(function(id){var n=state.nodes.find(function(x){return x.id===id;}); return n?n.name:'?';}).join(' → '); setStatus(names); var start=state.nodes.find(function(n){return n.id===from;}); showModal(start||{},t('Relatie gasita','Relation found'),names); history.replaceState(null,'','arborele-satului.html?from='+encodeURIComponent(from)+'&to='+encodeURIComponent(to)); }
function bindEvents(){ els.findRelation.addEventListener('click',handleFindRelation); els.fitView.addEventListener('click',function(){ fitGraph(); setStatus(t('Arborele a fost recentrat.','Tree re-centered.')); }); els.clearSelection.addEventListener('click',function(){ state.highlightedNodeIds.clear(); state.highlightedLinkKeys.clear(); state.selectedNodeId=null; hideModal(); updateStyles(); fitGraph(450); history.replaceState(null,'','arborele-satului.html'); }); els.familySearch.addEventListener('change',function(){ var node=state.nodes.find(function(n){return norm(n.name)===norm(els.familySearch.value);}); if(!node){setStatus(t('Familia cautata nu a fost gasita.','Searched family not found.')); return;} history.replaceState(null,'','arborele-satului.html?family='+encodeURIComponent(node.id)); state.selectedNodeId=node.id; state.highlightedNodeIds=new Set([node.id]); state.highlightedLinkKeys=new Set(); updateStyles(); centerOnNode(node,1.5); showModal(node,node.name,node.visibility==='public'?t('Ai selectat familia din cautare.','You selected the family from search.'):t('Familia este privata.','Family is private.')); }); els.treeContainer.addEventListener('click',function(ev){ if(ev.target===els.treeContainer||ev.target===els.svg) hideModal();}); window.addEventListener('resize',function(){ var rect=els.treeContainer.getBoundingClientRect(); state.width=Math.max(400,rect.width); state.svg.attr('viewBox',[0,0,state.width,state.height]); if(state.simulation){ state.simulation.force('center',d3.forceCenter(state.width/2,state.height/2)); state.simulation.alpha(0.25).restart(); setTimeout(function(){fitGraph(350);},220);} }); }
async function init(){ try{ initLang(); initScroll(); initHamburger(); setStatus(t('Se incarca familiile si relatiile...','Loading families and connections...')); initSvg(); var graph=await loadGraph(); state.nodes=graph.nodes; state.links=graph.links; state.adj=buildAdj(graph.nodes,graph.links); populateControls(); bindEvents(); drawGraph(); }catch(err){ console.error(err); setStatus(t('Eroare la incarcarea datelor din Supabase.','Error loading data from Supabase.')); if(els.modal){ els.modal.classList.remove('hidden'); els.modalTitle.textContent=t('Eroare','Error'); els.modalText.textContent=(err&&err.message)||String(err); } } }
init();
})();
